In [22]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup

In [23]:
df = pd.read_html("https://en.wikipedia.org/wiki/Super_Bowl_television_ratings")

In [24]:
df = df[0]

In [25]:
df.head()

  Super Bowl              Date Network Avg. viewers (millions)  \
  Super Bowl              Date Network Avg. viewers (millions)
0          I  January 15, 1967     CBS               26.75[13]
1          I  January 15, 1967     NBC               24.43[13]
2         II  January 14, 1968     CBS               39.12[13]
3        III  January 12, 1969     NBC               41.66[13]
4         IV  January 11, 1970     CBS               44.27[13]

  Avg. Halftime Show Viewers (millions) Households         18–49 demographic  \
  Avg. Halftime Show Viewers (millions)     Rating   Share            Rating
0                                   NaN   22.6[13]  43[13]          Un­known
1                                   NaN   18.5[13]  36[13]          Un­known
2                                   NaN   36.8[13]  68[13]          Un­known
3                                   NaN   36.0[13]  70[13]          Un­known
4                                   NaN   39.4[13]  69[13]          Un­known

            Avg. cost of 30-second ad
      Share                  Original 2023 inflation- adjusted
0  Un­known               $42,500[13]                 $388,353
1  Un­known               $37,500[13]                 $342,665
2  Un­known               $54,500[13]                 $477,514
3  Un­known               $55,000[13]                 $456,969
4  Un­known               $78,200[13]                 $613,538

In [27]:
url = 'https://en.wikipedia.org/wiki/List_of_Super_Bowl_champions'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table', {'class': 'wikitable'})
second_table = tables[1]  # The second table

df2 = pd.read_html(str(second_table))[0]

df2.head()

,Game,Date (Season),Winning team,Score,Losing team,Venue,City,Attendance,Referee,Ref.
0,I [sb 1],"January 15, 1967 (1966 AFL/1966 NFL)","Green Bay Packersn (1, 1–0)",35–10,"Kansas City Chiefsa (1, 0–1)",Los Angeles Memorial Coliseum,"Los Angeles, California[sb 2]",61946,Norm Schachter,[7][8]
1,II [sb 1],"January 14, 1968 (1967 AFL/1967 NFL)","Green Bay Packersn (2, 2–0)",33–14,"Oakland Raidersa (1, 0–1)",Miami Orange Bowl,"Miami, Florida[sb 3]",75546,Jack Vest,[9][8]
2,III [sb 1],"January 12, 1969 (1968 AFL/1968 NFL)","New York Jetsa (1, 1–0)",16–7,"Baltimore Coltsn (1, 0–1)",Miami Orange Bowl (2),"Miami, Florida (2)[sb 3]",75389,Tom Bell,[10][8]
3,IV [sb 1],"January 11, 1970 (1969 AFL/1969 NFL)","Kansas City Chiefsa (2, 1–1)",23–7,"Minnesota Vikingsn (1, 0–1)",Tulane Stadium,"New Orleans, Louisiana",80562,John McDonough,[11][8]
4,V,"January 17, 1971 (1970)","Baltimore ColtsA (2, 1–1)",16–13,"Dallas CowboysN (1, 0–1)",Miami Orange Bowl (3),"Miami, Florida (3)[sb 3]",79204,Norm Schachter,[12][8]